name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: golive123/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'nodejs'
      appName: 'user'
    ssecrets:
      azuresecrets: ${{ secrets.azuresecrets }}

