name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: udayach123/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'nodejs'
      appName: 'user'
#    secrets:
#      vault_token: ${{ secrets.vault_token }}

